project:
  type: website
  resources:
    - files/**

website:
  title: "William Ortega | Engineering Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects
      - href: leadership.qmd
        text: Leadership
      - href: resume.qmd
        text: Resume
page-footer:
  center: "William Ortega | Harvey Mudd College"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



